apiVersion: v1
kind: Service
metadata:
  name: hospital-sqlserver
  namespace: hospital
spec:
  selector:
    app: hospital-sqlserver
  ports:
    - port: 1433
      targetPort: 1433
  clusterIP: None  # Headless service，配合 StatefulSet 实现稳定 DNS
