apiVersion: v1
kind: Secret
metadata:
  name: hospital-api-secret
  namespace: hospital
type: Opaque
stringData:
  JwtSettings__SecretKey: "ThisIsADevelopmentSecretKey_MustBeAtLeast32Characters!"
  JwtSettings__Issuer: "HospitalApi"
  JwtSettings__Audience: "HospitalApp"
  JwtSettings__ExpirationHours: "24"
  SA_PASSWORD: "Hospital@2024"
